Added kafka and docker-compose
2desoo/task-restful pull request #2
Opened 2024-12-12 02:19 UTC by 2desoo

2024-12-13 11:57 UTC, Alexandr056 requested changes
нет отправки уведомления при изменении статуса

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/config/KafkaConfig.java
> +    @Bean("client")
просто клиент не раскрывает суть, стоит использовать более говорящие названия

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @Value("${kafka.topic}")
отступ + топик можно было сделать бином через NewTopic

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
а надо ли здесь указывать ok?

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
а надо ли здесь указывать ok?

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
а надо ли здесь указывать ok?

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientConsumer.java
> +    public void listener(@Payload List<ClientDto> messages,
еще бы ack не игнорировать

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientProducer.java
> +            kafkaTemplate.sendDefault(UUID.randomUUID().toString(), id).get();
get не очень хорошо использовать тут, на уроке говорили почему…
блокирующий вызов

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientProducer.java
> +            kafkaTemplate.send(topic, o).get();
get не очень хорошо использовать тут, на уроке говорили почему…
блокирующий вызов

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/model/Client.java
> +@Entity
так же Table что бы отвязать имя таблицы от имени класса + возможны доп настройки

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/service/impl/TaskServiceImpl.java
> +    public TaskDto updateTask(Long id, TaskDto updatedTaskDto) {
а где отправка уведомления при изменении статуса task?

2024-12-13 11:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/service/impl/ClientServiceImpl.java
> +public class ClientServiceImpl implements ClientService {
код с урока, в заднии этого не было

2024-12-16 14:48 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
Убрал

2024-12-16 14:48 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
Убрал

2024-12-16 14:48 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/controller/ClientController.java
> +    @ResponseStatus(HttpStatus.OK)
Убрал

2024-12-16 14:50 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientConsumer.java
> +    public void listener(@Payload List<ClientDto> messages,
Исправил

2024-12-16 14:58 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientProducer.java
> +            kafkaTemplate.sendDefault(UUID.randomUUID().toString(), id).get();
Убрал

2024-12-16 14:58 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/kafka/KafkaClientProducer.java
> +            kafkaTemplate.send(topic, o).get();
Убрал

2024-12-16 14:58 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/model/Client.java
> +@Entity
Добавил

2024-12-16 15:00 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/service/impl/ClientServiceImpl.java
> +public class ClientServiceImpl implements ClientService {
Убрал лишнее

2024-12-16 15:10 UTC, 2desoo commented on src/main/java/com/dubrovsky/task/restful/config/KafkaConfig.java
> +    @Bean("client")
Исправил

2024-12-17 07:57 UTC, Alexandr056 approved these changes

2024-12-17 07:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/config/KafkaConfig.java
> +    @Bean("clientKafkaTemplate")
тут бы назвать что за клиент) что-что отражающее его суть, задачу которую выполняет

2024-12-17 07:57 UTC, Alexandr056 commented on src/main/java/com/dubrovsky/task/restful/service/impl/TaskServiceImpl.java
> +            sendStatusChangeNotification(String.valueOf(task));
лучше переопределить метод toString у Task, сможете переиспользовать

2024-12-17 07:57 UTC, Alexandr056 commented
хорошая работа над ошибками

2024-12-18 20:34 UTC, merged